import React from "react";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
// import { dark } from "@clerk/themes";

import "../globals.css";

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={
        {
          // baseTheme: dark,
        }
      }
    >
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
